gpu_list:
    - 5
seed: null
dump_path: './outputs/'
defaults:
    - data: hk_hybrid
    - data/dataset: hkhybrid_pointnet
    - model: regression
    - model/feature_extractor: pointnet
    - model/regression_alg: linear
    - engine: regression
    - tasks/train: train_pointnet
    - optimizers@tasks.train.optimizers: adam
    - loss@tasks.train.loss: mse
    - sampler@tasks.train.data_loaders.train.sampler: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler: subset_random
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_
